### ISSUE TITLE
LIL storage and 1-D sparse tensors

### ISSUE THREAD

**Issue by JohanMabille** [xtensor-stack/xtensor-sparse#8]
The current LIL implementation cannot be used for 1-D sparse tensors. Since we don't want a specific implementation for 1-D, the only solution I see for the moment is to add another map to the container, and switch between them based on the dimension of the tensor:

```cpp
using index_type = size_type;
using list_index_type = std::vector<index_type>;
using container_type = std::map<list_index_type, std::map<index_type, value_type>>;
using container_type_1d = std::map<index_type, value_type>;

shape_type m_shape;
container_type m_data;
container_type_1d m_data_1d;
```

**Comment by gouarin** [comment]
I think LIL matrix is not a good name since we use a map.

And we should be able to use the same implementation for 1-D and N-D tensors by using the following data structure

```cpp
using index_type = size_type;
using list_index_type = tensor<index_type, 1>;
using container_type = std::map<list_index_type, value_type>;

shape_type m_shape;
container_type m_data;
```

When we need to reshape, we just have to modify in-place the list of index.

The problem I see here is that a map has a limit of memory size which is small. And we have to make a benchmark of the modification of the indices when you have around 1 million elements.

**Comment by JohanMabille** [comment]
Indeed this storage (i.e. a simple map) is more flexible. I think the list_index_type should be a svector. This way wa avoid dynamic allocations for dimensions < 4.

I agree that we should change the name.

**Comment by gouarin** [comment]
This is finally what I made: use a svector !

**Comment by JohanMabille** [comment]
This has been implemented.
